### ISSUE TITLE
Copilot notifications are being sent repeatedly

### ISSUE THREAD

**Issue by parthshah** [topcoder-platform/tc-connect-notifications#17]
it doesn't look like x-delay is being handled correctly.

**Comment by uttpal** [comment]
@parthshah I think there is no delay added to the published message so its gets published without delay. shall i fix it?

**Comment by parthshah** [comment]
➤ Parth commented:
Thanks. Yup, delay was missing. Also it was publishing through the wrong exchange. This is fixed now though.
