### ISSUE TITLE
No email notification on creating a project

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/tc-connect-notifications#19]
1. Login as cp-superstar; (copilot)
2. Create a project and observe

Actual:

There is no email notification received for creating a project

Expected:

Email notification should be sent on creating a project.

**Comment by nithyaasworld** [comment]
![image](https://cloud.githubusercontent.com/assets/5114190/22397452/8afe6dd0-e597-11e6-84f2-e8a9fcc7af2b.png)

**Comment by harrywynn** [comment]
@parthshah is this because the user creating the project is a copilot?

**Comment by parthshah** [comment]
I'm not able to reproduce this. Emails are coming through.
