### ISSUE TITLE
Notify slack channels for specific event types

### ISSUE THREAD

**Issue by parthshah** [topcoder-platform/tc-connect-notifications#2]
Integration to slack will be done through Cloudamqp's webhook feature. 
Event types
* Project created
* Project available for review
* Project available to claim - should send reminders ever 12 hours (configurable) if project is not yet claimed by co-pilots.

**Comment by parthshah** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Integration to slack will be done through Cloudamqp's webhook feature. Event types  Project created Project available for review Project available to claim - should send reminders ever 12 hours (configurable) if project is not yet claimed by co-pilots.](https://trello.com/c/qyO6523k/1-integration-to-slack-will-be-done-through-cloudamqp-s-webhook-feature-event-types-project-created-project-available-for-review-p)

**Comment by parthshah** [comment]
Challenge Link: https://www.topcoder.com/direct/contest/detail.action?projectId=30056134

**Comment by harrywynn** [comment]
Updated code on https://github.com/appirio-tech/tc-connect-notifications/tree/tc_1/remote

**Comment by parthshah** [comment]
👍  awesome. I'll go through this and let you know if I have any questions.
