### ISSUE TITLE
No slack bot notification when creation a Project

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#21]
Description
-----------------------------------------------------------------
No slack bot notification when creation a Project

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a Valid User [Manager] pat_monahan; topcoder123!

- In the Project View

- Create a Project

Actual Result(s)
-----------------------------------------------------------------
- Must display a notification in the channel #connect-bughunt

Expected Result(s)
-----------------------------------------------------------------
- No slack bot notification when creation a Project

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):**  Chrome 56.0.2924.76

**Comment by harrywynn** [comment]
Slack notifications are only posted for:
-- Project moves from “Draft” to “In Review” (managers)
-- Project moves from “In Review” to “Review” (copilots)
-- Project isn’t claimed - repost every 12 hours (copilots)
