### ISSUE TITLE
The Email notification received after Submitting for review has broken link and broken image

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/tc-connect-notifications#22]
1. Login as a copilot
2. Create a project and submit for review
3. Observe the email notification received

Actual:

Email has a broken image. Clicking on it leads to a 404 error.

Expected:

No broken image. No broken link.

**Comment by nithyaasworld** [comment]
![image](https://cloud.githubusercontent.com/assets/5114190/22397468/1f1d392e-e598-11e6-9bd7-c4e72183a35d.png)

Clicking on the above link leads to below error:

![image](https://cloud.githubusercontent.com/assets/5114190/22397476/3b98aee4-e598-11e6-9953-c74eb6ebbf14.png)

**Comment by parthshah** [comment]
Probably a conflict with CSS styles w/ mailinator.
