### ISSUE TITLE
Not getting emails for New posts and replies on Dashboard and Discussions

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#23]
Description
-----------------------------------------------------------------
Not getting emails for New posts and replies on Dashboard and Discussions

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a Valid User [Manager] pat_monahan; topcoder123!

- In the Project View

- Create a Project and click on it

- Click 'discussions' and add a message

Actual Result(s)
-----------------------------------------------------------------
- Not getting emails for New posts and replies on Dashboard and Discussions

Expected Result(s)
-----------------------------------------------------------------
- Must get an email

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):**  Chrome 56.0.2924.76

**Comment by parthshah** [comment]
Outside the scope of this project, but emails are not sent to the person creating the post.
