### ISSUE TITLE
No email notification after a project is reviewed

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/tc-connect-notifications#26]
1. Login as copilot
2. Create a project and submit for review
3. Login as manager and join the project and then mark the project as Reviewed
4. observe the email

Actual:

No email is sent to the copilot 

Expected:

Email notification should be sent stating that project has been reviewed.

**Comment by harrywynn** [comment]
@parthshah is this because the user that created the project is a copilot and not a general user?  If I test in a scenario where the creating user was a regular user the notification works as expected.

**Comment by parthshah** [comment]
After the discourse setting change to always send notifications regardless of whether the user has read the post, I'm receiving all emails.
