### ISSUE TITLE
Co-pilot's replies didn't received to manager

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#27]
Description
-----------------------------------------------------------------
Co-pilot's replies didn't received to manager

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a Copilot

- In the Project View; Click on the Project (http://connect.topcoder-dev.com/projects/603)

- Click 'discussions' and add a message

- Check the manager inbox

Actual Result(s)
-----------------------------------------------------------------
- Co-pilot's replies didn't received to manager

Expected Result(s)
-----------------------------------------------------------------
- Must get an email with co-pilot's message

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by harrywynn** [comment]
<img width="716" alt="screen shot 2017-01-29 at 10 41 34 am" src="https://cloud.githubusercontent.com/assets/103879/22405365/8d50d848-e60f-11e6-8c1e-0444a7ff709d.png">
