### ISSUE TITLE
No Inbox-notification after a project has been reviewed

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/tc-connect-notifications#28]
Login as copilot
Create a project and submit for review
Login as manager and join the project and then mark the project as Reviewed
observe the Inbox-notification of both the users

Actual:

No inbox notification once the project is marked as reviewed.

Expected:

Inbox-notification should be sent upon marking the project as reviewed.

**Comment by nithyaasworld** [comment]
![image](https://cloud.githubusercontent.com/assets/5114190/22397552/d15bff70-e599-11e6-9bb3-5cc62712715d.png)

**Comment by harrywynn** [comment]
@parthshah is this because the creating user was a copilot?

**Comment by parthshah** [comment]
After the discourse setting change to always send notifications regardless of whether the user has read the post, I'm receiving all emails.
