### ISSUE TITLE
On leaving a project, the message is not displayed at the top (Inbox-Notification)

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/tc-connect-notifications#32]
1. Login as manager of project
2. Leave the project 
3. Login as copilot of the same project
4. Observe the inbox notification

Actual:

Inbox Notification is not shown at the top

Expected:

Latest Notification should be shown at the top.

**Comment by nithyaasworld** [comment]
![image](https://cloud.githubusercontent.com/assets/5114190/22397638/28de4ec2-e59c-11e6-89fe-57932ad249cb.png)

**Comment by parthshah** [comment]
I wonder if someone cancelled the project after removing a certain user. I'm seeing the latest notifications on top.
