### ISSUE TITLE
No E-Mail notification for project status change "Complete"

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#36]
Description
-----------------------------------------------------------------
No E-Mail notification for project status change "Complete"

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a Manager

- In the Project View; Click on the Project (http://connect.topcoder-dev.com/projects/604)

- In the 'Dashboard'

- Change the status to 'Complete'

- Check the email

Actual Result(s)
-----------------------------------------------------------------
- No E-Mail notification for project status change "Complete"

Expected Result(s)
-----------------------------------------------------------------
- Must received an email Manager/Copilot/Users

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![1 4](https://cloud.githubusercontent.com/assets/4592712/22398002/a26c489a-e5a4-11e6-82a1-e1622374ec76.png)
![1 2](https://cloud.githubusercontent.com/assets/4592712/22398000/a2678710-e5a4-11e6-98ca-3e7378df9885.png)
![1 3](https://cloud.githubusercontent.com/assets/4592712/22398001/a26becf6-e5a4-11e6-912b-31655b5ba51b.png)

**Comment by parthshah** [comment]
After the discourse setting change to always send notifications regardless of whether the user has read the post, I'm receiving all emails.
