### ISSUE TITLE
No 'Project Dashboard' message for project status change "Complete"

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#37]
Description
-----------------------------------------------------------------
No 'Project Dashboard' message for project status change "Complete"

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a Manager (pat_monahan)

- In the 'Dashboard', Create a New Project

- Set the users as follows (Manager: pat_monahan | Copilot: cp-superstar | Owner: christina_uw | Member: theo_ekis)

- Change the status to 'Complete'

- Check the 'Project Dashboard'

Actual Result(s)
-----------------------------------------------------------------
- No 'Project Dashboard' message for project status change "Complete"

Expected Result(s)
-----------------------------------------------------------------
- Must display a 'Project Dashboard' message for Manager/Copilot/Users

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![1 1](https://cloud.githubusercontent.com/assets/4592712/22398004/a5793c8c-e5a4-11e6-9b71-85de9c0f2fcd.png)

**Comment by harrywynn** [comment]
<img width="770" alt="screen shot 2017-01-29 at 10 54 53 am" src="https://cloud.githubusercontent.com/assets/103879/22405474/635d3296-e611-11e6-9d6e-2260ae5791b9.png">

Notifications are appearing, although possible out of order as noted in #32
