### ISSUE TITLE
No E-Mail notification for project status change "Canceled" for Managers

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#38]
Description
-----------------------------------------------------------------
No E-Mail notification for project status change "Canceled" for Managers

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a Manager

- In the Project View; Click on the Project (http://connect.topcoder-dev.com/projects/604)

- In the 'Dashboard'

- Change the status to 'Cancelled'

- Check the Manager email box

Actual Result(s)
-----------------------------------------------------------------
- No E-Mail notification for project status change "Canceled" for Managers

Expected Result(s)
-----------------------------------------------------------------
- Must received an email to the Manager. Copilot/Users gets the message

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![2](https://cloud.githubusercontent.com/assets/4592712/22398044/2ab0fbba-e5a5-11e6-8aba-32aee2ce10c4.png)

**Comment by harrywynn** [comment]
<img width="989" alt="screen shot 2017-01-29 at 10 58 03 am" src="https://cloud.githubusercontent.com/assets/103879/22405513/eb0eaa94-e611-11e6-888e-e91df793dc09.png">

Not able to reproduce this.
