### ISSUE TITLE
No E-Mail notification for project status change to "Active" for Copilot/Users

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#39]
Description
-----------------------------------------------------------------
No E-Mail notification for project status change to "Active" for Copilot/Users

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a Manager (pat_monahan)

- In the 'Dashboard', Create a New Project

- Set the users as follows (Manager: pat_monahan | Copilot: cp-superstar | Owner: christina_uw | Member: theo_ekis)

- Change the status to 'Active'

- Check the email box of the Copilot/Users/Owner

Actual Result(s)
-----------------------------------------------------------------
- No E-Mail notification for project status change to "Active" for Copilot/Users. Only the manager gets the email notification. Check the 6.4.png

Expected Result(s)
-----------------------------------------------------------------
- Must received an email to Copilot/Users/Owner

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![6 4 - manager](https://cloud.githubusercontent.com/assets/4592712/22398518/149ae704-e5b0-11e6-8af4-12740d66c398.png)
![6 1-copilot](https://cloud.githubusercontent.com/assets/4592712/22398519/149b762e-e5b0-11e6-80f3-6244accbb71c.png)
![6 2 - owner](https://cloud.githubusercontent.com/assets/4592712/22398517/149ad084-e5b0-11e6-8cf3-bf8be7bbf13f.png)
![6 3 - user](https://cloud.githubusercontent.com/assets/4592712/22398516/149ac760-e5b0-11e6-80da-bfc027ebf78e.png)

**Comment by harrywynn** [comment]
<img width="992" alt="screen shot 2017-01-29 at 11 04 43 am" src="https://cloud.githubusercontent.com/assets/103879/22405560/c3619bd6-e612-11e6-8ea2-18ced8b131e3.png">

<img width="1004" alt="screen shot 2017-01-29 at 11 05 19 am" src="https://cloud.githubusercontent.com/assets/103879/22405570/de2f2104-e612-11e6-8728-c37b92341291.png">

<img width="984" alt="screen shot 2017-01-29 at 11 06 04 am" src="https://cloud.githubusercontent.com/assets/103879/22405577/f3f67d98-e612-11e6-963d-cc71ded3af8d.png">

Not able to reproduce this.  All users involved received emails.
