### ISSUE TITLE
No 'Project Dashboard' message for project status change "Active"

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#40]
Description
-----------------------------------------------------------------
No 'Project Dashboard' message for project status change "Active"

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a Manager (pat_monahan)

- In the 'Dashboard', Create a New Project

- Set the users as follows (Manager: pat_monahan | Copilot: cp-superstar | Owner: christina_uw | Member: theo_ekis)

- Change the status to 'Active'

- Check the 'Project Dashboard'

Actual Result(s)
-----------------------------------------------------------------
- No 'Project Dashboard' message for project status change "Active"

Expected Result(s)
-----------------------------------------------------------------
- Must display a 'Project Dashboard' message for Manager/Copilot/Users

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by harrywynn** [comment]
<img width="765" alt="screen shot 2017-01-29 at 11 08 00 am" src="https://cloud.githubusercontent.com/assets/103879/22405599/3b35270e-e613-11e6-9975-240d61e2151e.png">

Not able to reproduce - message is displaying as expected.
