### ISSUE TITLE
No 'Project Dashboard' message for project status change to "Cancelled" for Manager

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#41]
Description
-----------------------------------------------------------------
No 'Project Dashboard' message for project status change to "Cancelled" for Manager

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a Manager (pat_monahan)

- In the 'Dashboard', Create a New Project

- Set the users as follows (Manager: pat_monahan | Copilot: cp-superstar | Owner: christina_uw | Member: theo_ekis)

- Change the status to 'Cancelled'

- Check the 'Project Dashboard' message

Actual Result(s)
-----------------------------------------------------------------
- No 'Project Dashboard' message for project status change to "Cancelled" for Manager

Expected Result(s)
-----------------------------------------------------------------
- Must display a 'Project Dashboard' message for the Manager

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![3 2](https://cloud.githubusercontent.com/assets/4592712/22398109/bfd775ec-e5a6-11e6-9236-b0adc38f7f42.png)
![Uploading 3.1.png…]()

**Comment by harrywynn** [comment]
<img width="779" alt="screen shot 2017-01-29 at 11 10 14 am" src="https://cloud.githubusercontent.com/assets/103879/22405623/9ef11e06-e613-11e6-8146-4f567f90a6d3.png">

Not able to reproduce this.
http://connect.topcoder-dev.com/projects/620
