### ISSUE TITLE
No Email notification when the project status changed to "In-Review" for Managers

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#42]
Description
-----------------------------------------------------------------
No Email notification when the project status changed to "In-Review" for Managers

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a Manager (pat_monahan)

- In the 'Dashboard', Create a New Project

- Set the users as follows (Manager: pat_monahan | Copilot: cp-superstar | Owner: christina_uw | Member: theo_ekis)

- Change the status to 'In-Review'

- Check the email of the Manager

Actual Result(s)
-----------------------------------------------------------------
- No Email notification when the project status changed to "In-Review" for Managers

Expected Result(s)
-----------------------------------------------------------------
- Must receive Email notification for Managers

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![4 2](https://cloud.githubusercontent.com/assets/4592712/22398381/42adc9ca-e5ad-11e6-93be-94f91f8d09ef.png)
![4 1](https://cloud.githubusercontent.com/assets/4592712/22398380/42ad5f1c-e5ad-11e6-8fe5-2a326a4cd5a5.png)

**Comment by harrywynn** [comment]
@parthshah should the manager receive a notification in this instance?

**Comment by parthshah** [comment]
Yes they should. I verified that the managers are receiving emails. I have a feeling this inconsistency must be due to the default setting in discourse to send email notifications only if the user hasn't already read the post (via dashboard). I've changed this setting now.
