### ISSUE TITLE
No slack notification when the project status changed to "Reviewed" by Owner

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#43]
Description
-----------------------------------------------------------------
No slack notification when the project status changed to "Reviewed" by Owner

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a Manager (pat_monahan)

- In the 'Dashboard', Create a New Project

- Set the users as follows (Manager: pat_monahan | Copilot: cp-superstar | Owner: christina_uw | Member: theo_ekis)

- Change the status to 'In-Review'

- Login as a Owner (christina_uw)

- Change the status to 'Reviewed'

- Check the slack

Actual Result(s)
-----------------------------------------------------------------
- No slack notification when the project status changed to "Reviewed" by Owner

Expected Result(s)
-----------------------------------------------------------------
- Must display a slack notification 

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![8 3](https://cloud.githubusercontent.com/assets/4592712/22399088/7fa8024c-e5bb-11e6-996e-94f545100e65.png)
![8 1](https://cloud.githubusercontent.com/assets/4592712/22399087/7fa7fc2a-e5bb-11e6-811d-e01d897e4832.png)
![8 2](https://cloud.githubusercontent.com/assets/4592712/22399086/7fa766c0-e5bb-11e6-9a11-8ed61ece5471.png)

**Comment by harrywynn** [comment]
@parthshah is this due to the Owner marking it as Reviewed instead of a Manager?

**Comment by parthshah** [comment]
Owners / customers don't have the option of changing project status from 'in_review' to 'reviewed'. So the user must have used either the copilot or manager accounts to make the switch. In any case, notifications to copilots asking to claim a project should be sent only if a copilot has *not* been assigned to the project. Looks like a copilot was already added to this project, prior to switching the status.
