### ISSUE TITLE
In the event of the 'Ownership' change; only one users gets the notification email

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#44]
Description
-----------------------------------------------------------------
In the event of the 'Ownership' change; only one users gets the notification email

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a User (christina_uw)

- In the 'Dashboard', Create a New Project

- Set the users as follows (User: pat_monahan | User: cp-superstar | Owner: christina_uw | User: theo_ekis)

- Now make 'Patrick Monahan' as the Owner of the project

- Check the email of the 'pat_monahan' --> Received

- Others - NO EMails

Actual Result(s)
-----------------------------------------------------------------
- In the event of the 'Ownership' change; only one users gets the notification email

Expected Result(s)
-----------------------------------------------------------------
- Must receive Email notification for Others as well

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![9](https://cloud.githubusercontent.com/assets/4592712/22401918/bd24caa6-e60b-11e6-8e55-8d76a62259dc.png)

https://www.screencast.com/t/q9TTpCNUtor

**Comment by harrywynn** [comment]
<img width="989" alt="screen shot 2017-01-29 at 11 38 19 am" src="https://cloud.githubusercontent.com/assets/103879/22405912/753a950c-e617-11e6-8be4-8cf2175641ed.png">

<img width="987" alt="screen shot 2017-01-29 at 11 38 50 am" src="https://cloud.githubusercontent.com/assets/103879/22405916/8682d31a-e617-11e6-9aa7-9562c51d1a06.png">

<img width="989" alt="screen shot 2017-01-29 at 11 39 16 am" src="https://cloud.githubusercontent.com/assets/103879/22405922/966b12c4-e617-11e6-8670-12f30eed6779.png">

<img width="996" alt="screen shot 2017-01-29 at 11 39 45 am" src="https://cloud.githubusercontent.com/assets/103879/22405926/a6d1acb8-e617-11e6-8cfc-814e73270c68.png">

Unable to reproduce, all users received emails.
