### ISSUE TITLE
Adding a Owner will display normal user notification in Project Dashboard Notification

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#45]
Description
-----------------------------------------------------------------
Adding a Owner will display normal user notification in Project Dashboard Notification

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a User (pat_monahan)

- In the 'Dashboard', Create a New Project

- Set the users as follows (Manager: pat_monahan | Owner: christina_uw )

- Adding 'christina_uw' will ask to add her as the Owner of the project

- Check the Project Dashboard Notification

Actual Result(s)
-----------------------------------------------------------------
- Adding a Owner will display normal user notification in Project Dashboard Notification

Expected Result(s)
-----------------------------------------------------------------
- Must display Owner notification in Project Dashboard Notification

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![11](https://cloud.githubusercontent.com/assets/4592712/22402451/50963c5a-e61d-11e6-88fd-cad3f73539e7.png)

**Comment by harrywynn** [comment]
@parthshah what's the expected notification wording here?

**Comment by parthshah** [comment]
Don't think we covered this case in the specs. I think having a more explicit message 'Your project has a new owner' would be more appropriate. 
@fnisen thoughts?

**Comment by fnisen** [comment]
This is a valid bug. @sdgun's suggested message is actually the copy from the spec (plus exclamation point). 😄 I think we missed the case of a manager creating a project and thus the first member added becoming automatically the owner. Can we support this one?

**Comment by parthshah** [comment]
Yes we can

**Comment by fnisen** [comment]
Yes, that copy is good.
