### ISSUE TITLE
One user won't get "Your project has a new owner" E-Mail notification

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#46]
Description
-----------------------------------------------------------------
One user won't get "Your project has a new owner" E-Mail notification

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a User (christina_uw)

- In the 'Dashboard', Create a New Project

- Set the users as follows (User: cp-superstar)

- Project Team looks like this [Owner: christina_uw | User: cp-superstar]

- Now make 'cp-superstar' as Owner of the project

- Check the Two E-Mails, both of them gets the "Your project has a new owner" E-Mail notification

- Login as a User (cp-superstar)

- Project Team looks like this [Owner: cp-superstar | User: christina_uw]

- Now make 'christina_uw' as Owner of the project

- Check the Two E-Mails, Only one gets the email

Actual Result(s)
-----------------------------------------------------------------
- One user won't get "Your project has a new owner" E-Mail notification 

Expected Result(s)
-----------------------------------------------------------------
- Must receive the email to both people

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![13 2](https://cloud.githubusercontent.com/assets/4592712/22405893/36ca5246-e66f-11e6-9b04-a60e2deea081.png)
![13 1](https://cloud.githubusercontent.com/assets/4592712/22405892/36c64b1a-e66f-11e6-88b5-2180b4f6b0e1.png)

**Comment by harrywynn** [comment]
<img width="990" alt="screen shot 2017-01-30 at 10 17 20 am" src="https://cloud.githubusercontent.com/assets/103879/22428514/56e1df7a-e6d5-11e6-80c2-69c6ef0f1544.png">

<img width="986" alt="screen shot 2017-01-30 at 10 16 33 am" src="https://cloud.githubusercontent.com/assets/103879/22428519/594f78a8-e6d5-11e6-94f6-0204436c3f14.png">

Not able to reproduce.
