### ISSUE TITLE
No Slack Notification for reminder of 12hr for non-claim

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#47]
Description
-----------------------------------------------------------------
No Slack Notification for reminder of 12hr for non-claim projects

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a User (pat_monahan)

- In the 'Dashboard', Create a New Project

- Set the users as follows (User: pat_monahan | Owner: christina_uw | User: theo_ekis)

- Adding 'christina_uw' will ask to add her as the Owner of the project

- Change the status to 'In-Review' by Manager

- Change the status to 'Reviewed' by Manager

- You can see a message in the slack (A project has been reviewed and needs a copilot. Please check it out and claim it. - P19 - Manager (In-Review and Reviewed))

- Wait more than 12hr

- Check the slack notification

Actual Result(s)
-----------------------------------------------------------------
- No Slack Notification for reminder of 12hr for non-claim

Expected Result(s)
-----------------------------------------------------------------
- Must trigger a slack notification

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
Please check the following example contests:
http://connect.topcoder-dev.com/projects/643
http://connect.topcoder-dev.com/projects/644

https://www.screencast.com/t/fNHS0l1N

**Comment by parthshah** [comment]
Tested in production, it works.
