### ISSUE TITLE
'Project Dashboard' message order is not consistent

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#48]
Description
-----------------------------------------------------------------
'Project Dashboard' message order is not consistent

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a User (pat_monahan)

- In the 'Dashboard', Create a New Project (Create a Other Work Project)

- Check the 'Project Dashboard' message order

- Login as a User (pat_monahan)

- In the 'Dashboard', Create a New Project (Create as Visualize an app idea/Prototype an app/Fully develop an app")

- Check the 'Project Dashboard' message order

Actual Result(s)
-----------------------------------------------------------------
- 'Project Dashboard' message order is not consistent

Expected Result(s)
-----------------------------------------------------------------
- 'Project Dashboard' message order must consistent in all occurrence. There are 3 messages the order must be the same in all created projects

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
https://www.screencast.com/t/b68jvamEt

**Comment by parthshah** [comment]
I understand the confusion here, let me clarify. Messages titled 
_'Hello, Coder here! your project has been created successfully' & 'Hey there, I'm ready with the next steps for your project!'_ are from an earlier integration which will be disabled once connect-notifications feature is live. The only message that will be displayed will be _'Your project has been created, and we're... '_.
@harrywynn I'll leave it you to decide whether this bug should be considered valid or not. I'm marking it resolved.
