### ISSUE TITLE
No E- Mail notification for creating a Project as 'Other Work' for Manager

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#49]
Description
-----------------------------------------------------------------
No E- Mail notification for creating a Project as 'Other Work' for Manager

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a User (pat_monahan)

- In the 'Dashboard', Create a New Project (Create a Other Work Project)

- Enter Project Name and Description

- Check the Manager E-Mail

Actual Result(s)
-----------------------------------------------------------------
- No E- Mail notification for creating a Project as 'Other Work' for Manager

Expected Result(s)
-----------------------------------------------------------------
- Must receive the 3 e-mail notifications received when manager creates "Visualize an app idea/Prototype an app/Fully develop an app"

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![16](https://cloud.githubusercontent.com/assets/4592712/22410509/4bfefcb6-e6bf-11e6-9dbb-bd33d10de951.png)

**Comment by parthshah** [comment]
@harrywynn - discourse's default behavior is to send email notifications only if the user hasn't already read that post / comment within a configurable (currently set to 1 min) time after the post / comment was created. I just changed the default to always send an email notification.
Marking this as resolved.
