### ISSUE TITLE
BOLD and Italic is not displayed in the E-Mail Notification Properly when user create a Dashboard Notification

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#50]
Description
-----------------------------------------------------------------
BOLD and Italic is not displayed in the E-Mail Notification Properly when user create a Dashboard Notification

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a User (pat_monahan)

- In the 'Dashboard', Create a New Project

- Set the users as follows (User: pat_monahan | Copilot: cp-superstar | Owner: christina_uw | User: theo_ekis)

- Add a Dashboard Notification as Follows

Hi, I am a robot and this is **BOLD** text and I have to _Italic_ it.
​
> Here goes the Quote.....
​
- This is Step one
- This is Step two
- This is Step three

1. This is bullet point one
2. This is bullet point two
3. This is bullet point three
​
End

- Check the E-Mail

Actual Result(s)
-----------------------------------------------------------------
- BOLD and Italic is not displayed in the E-Mail Notification Properly when user create a Dashboard Notification

Expected Result(s)
-----------------------------------------------------------------
- Must display the BOLD and ITALIC text in the email

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
This issue is; in the email there is a space after the text before '*' or '_'  -->  **BOLD ** /  _Italic _
![17](https://cloud.githubusercontent.com/assets/4592712/22410676/55a71b7a-e6c1-11e6-87e0-6034852bfbbe.png)

**Comment by harrywynn** [comment]
Closing as duplicate/related to #51
