### ISSUE TITLE
Bold/Italic/Bullet Points are not displayed in the Dashboard Notification when user create a Dashboard Notification

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#51]
Description
-----------------------------------------------------------------
Bold/Italic/Bullet Points are not displayed in the Dashboard Notification when user create a Dashboard Notification

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a User (pat_monahan)

- In the 'Dashboard', Create a New Project

- Set the users as follows (User: pat_monahan | Copilot: cp-superstar | Owner: christina_uw | User: theo_ekis)

- Add a Dashboard Notification as Follows

Hi, I am a robot and this is **BOLD** text and I have to _Italic_ it.
​
> Here goes the Quote.....
​
- This is Step one
- This is Step two
- This is Step three

1. This is bullet point one
2. This is bullet point two
3. This is bullet point three
​
End

- Check the E-Mail

Actual Result(s)
-----------------------------------------------------------------
- Bullet Points are not displayed in the Dashboard Notification when user create a Dashboard Notification

Expected Result(s)
-----------------------------------------------------------------
- Must display the bullet points in the Dashboard Notification

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![18](https://cloud.githubusercontent.com/assets/4592712/22410661/2c5a13a8-e6c1-11e6-8ca9-1a08a6ca9393.png)

**Comment by sdgun** [comment]
Also BOLD and ITALIC also not displayed.
This issue is; in the email there is a space after the text before '*' or '_' --> **BOLD ** / _Italic _

![17 1](https://cloud.githubusercontent.com/assets/4592712/22410760/4e1be894-e6c2-11e6-8d6f-daa251b4b37c.png)

**Comment by sdgun** [comment]
Same issue in the 'Discussions' section as well (Bold/Italic are not displayed in the 'Discussions' section)

![18 1](https://cloud.githubusercontent.com/assets/4592712/22412791/22ee9bc4-e6d8-11e6-87ea-3d711af1cb02.png)

**Comment by parthshah** [comment]
Seems like it's outside the scope of this project. This is a known issue being tracked in a different repo.
