### ISSUE TITLE
No Slack notification when 'Reviewed' in 'Other Work' Projects

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#52]
Description
-----------------------------------------------------------------
No Slack notification when 'Reviewed' in 'Other Work' Projects

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a User (pat_monahan)

- In the 'Dashboard', Create a New Project (Create a Other Work Project)

- Enter Project Name and Description

- Open the Project

- Set the users as follows (User: pat_monahan | Copilot: cp-superstar | Owner: christina_uw | User: theo_ekis)

- Change the status to 'In Review' (manager)

- Login as a User (Copilot: cp-superstar)

- Change the status to 'Reviewed' (Copilot)

- If NOT

- Login as a User (manager)

- Change the status to 'Reviewed' (manager)

- Tested Link: http://connect.topcoder-dev.com/projects/647

Actual Result(s)
-----------------------------------------------------------------
- No Slack notification when 'Reviewed' in 'Other Work' Projects

Expected Result(s)
-----------------------------------------------------------------
- Must display a slack notification

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![19](https://cloud.githubusercontent.com/assets/4592712/22410839/36c368a6-e6c3-11e6-8c51-99e0b45d1b3a.png)

**Comment by harrywynn** [comment]
The Slack notification isn't sent because the Copilot was already set when the project was created.  There can't be a copilot assigned when it's changed to "Reviewed".
