### ISSUE TITLE
[Common] Wrong hyperlinks in the Dashboard and E-Mail notifications

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#53]
Description
-----------------------------------------------------------------
[Common] Wrong hyperlinks in the Dashboard and E-Mail notifications

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a User (pat_monahan)

- In the 'Dashboard', Create a New Project 

- Open the Project

- Check the Dashboard notification hyperlinks and E-Mail hyperlinks

- All of the redirect the page to https

Actual Result(s)
-----------------------------------------------------------------
- Wrong hyperlinks in the Dashboard and E-Mail notifications

Expected Result(s)
-----------------------------------------------------------------
- Must load the page without any issue (https must --> http in the URL)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
https://www.screencast.com/t/VQv9eRqXD

![20 1](https://cloud.githubusercontent.com/assets/4592712/22412471/9b642dca-e6d4-11e6-820e-3e69069dc067.png)
![20 2](https://cloud.githubusercontent.com/assets/4592712/22412472/9b678f6a-e6d4-11e6-80a0-e5b6770e3526.png)

**Comment by parthshah** [comment]
All links should be prefixed with https protocol.
