### ISSUE TITLE
Sometimes projects created by Manager won't trigger e-mail notifications

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#54]
Description
-----------------------------------------------------------------
Sometimes projects created by Manager won't trigger e-mail notifications

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a User (pat_monahan)

- In the 'Dashboard', Create a New Project 

- Check the e-mail notification 

- Reproduce Rate 4/5, When you have do this after 1-2hr interval without doing anything to the system

Actual Result(s)
-----------------------------------------------------------------
- Sometimes projects created by Manager won't trigger e-mail notifications

Expected Result(s)
-----------------------------------------------------------------
- Must trigger e-mail notification

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
https://www.screencast.com/t/pG5PJlZd

**Comment by harrywynn** [comment]
@parthshah is this due to the creator being a manager?

**Comment by parthshah** [comment]
@harrywynn - discourse's default behavior is to send email notifications only if the user hasn't already read that post / comment within a configurable (currently set to 1 min) time after the post / comment was created. I just changed the default to always send an email notification. My tests show that emails are being sent right away.
