### ISSUE TITLE
No e-mail notification when Copilot Joins to a Project

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#55]
Description
-----------------------------------------------------------------
No e-mail notification when Copilot Joins to a Project

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a User (pat_monahan)

- In the 'Dashboard', Create a New Project

- Change the status to 'In-Review' by Manager

- Change the status to 'Reviewed' by Manager

- You can see a message in the slack (A project has been reviewed and needs a copilot. Please check it out and claim it. - P19 - Manager (In-Review and Reviewed))

- Click on that hyperlink

- Now Join to the project as copilot

- Check the copilot mail

- NOTE: After creating a Project by 'christina_uw'; Manager can Join to the project by clicking on the 'Join' button. Also it will trigger an email to the manager. But in the above case copilot won't receive any email

Actual Result(s)
-----------------------------------------------------------------
- No e-mail notification when Copilot Joins to a Project

Expected Result(s)
-----------------------------------------------------------------
- Must trigger e-mail notification for copilot

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by harrywynn** [comment]
<img width="990" alt="screen shot 2017-01-30 at 9 40 39 am" src="https://cloud.githubusercontent.com/assets/103879/22427213/44843666-e6d0-11e6-9d61-68e049de7013.png">

Not able to reproduce this after joining with the copilot account.
