### ISSUE TITLE
Manager won't receive e-mail notification when he/she left the project

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#56]
Description
-----------------------------------------------------------------
Manager won't receive e-mail notification when he/she left the project

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a User (pat_monahan)

- In the 'Dashboard', Create a New Project

- Now He is the Manager

- Click 'Leave Project'

- Check the Manager e-mail --> NO

- Click 'Join Project'

- Check the Manager e-mail --> YES
(If this is because he is the one who triggers this operation why he is receiving 'Join Project E-Mails')

Actual Result(s)
-----------------------------------------------------------------
- Manager won't receive e-mail notification when he/she left the project

Expected Result(s)
-----------------------------------------------------------------
- Must trigger e-mail notification for manager
- Manager is receiving e-mail notification when he/she joins to the projects. 
- (If this is because he is the one who triggers this operation why he is receiving 'Join Project E-Mails')

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![24](https://cloud.githubusercontent.com/assets/4592712/22415157/ee1e195c-e6ea-11e6-9e6a-e3165cfb2c27.png)

**Comment by harrywynn** [comment]
@parthshah is this the expected behavior here?

**Comment by parthshah** [comment]
This is the expected behavior at the moment. Although, I would like to add this as an enhancement. The verbiage of such a notification should be something like 'You've left the project. If you think this is a mistake please contact the project owner.' 
@fnisen ?

**Comment by fnisen** [comment]
@parthshah, @harrywynn I don't think we currently notify anyone when they've left: members, copilots, or managers. I'm just assuming for now that no one would remove themselves unintentionally b/c it's an action that has to be confirmed in the app. Managers can remove other managers or anyone on the project, and I'm assuming they wouldn't do this without the other person knowing. Same goes for owners. The chief complexity is that we have to implement different notifications for the same event based on role (for example, the person being removed and the one doing the removing should get different notifications; or a manager that added himself should get different copy than the rest of the team). @parthshah can we support this right now? It would be good, but doesn't feel like a "v1" need.

**Comment by parthshah** [comment]
Right, this is another one of those one of notifications that we dont support right now
