### ISSUE TITLE
All the previous mails received for the copilot after he/she joins to the project

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/tc-connect-notifications#57]
Description
-----------------------------------------------------------------
All the previous mails received for the copilot after he/she joins to the project

Steps to Reproduce
-----------------------------------------------------------------

- Open the http://connect.topcoder-dev.com/

- Login as a User (pat_monahan)

- In the 'Dashboard', Create a New Project

- Set the users as follows (User: pat_monahan | Owner: christina_uw | User: theo_ekis)

- Now Login as a User (christina_uw) and make (theo_ekis) as Owner

- Now Login as a User (theo_ekis) and make (christina_uw) as Owner

- Now Login as a User (pat_monahan) and Leave from the Project

- Now Login as a User (christina_uw)

- Add (pat_monahan) as a User

- Login as a User (Copilot: cp-superstar)

- Join to the Project

- Check the Copilot e-mail

Actual Result(s)
-----------------------------------------------------------------
- All the previous mails received for the copilot after he/she joins to the project

Expected Result(s)
-----------------------------------------------------------------
- Must not receive all the previous e-mails

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![25](https://cloud.githubusercontent.com/assets/4592712/22422040/55dca700-e710-11e6-8b34-4d878e8f2504.png)

**Comment by harrywynn** [comment]
<img width="986" alt="screen shot 2017-01-30 at 10 34 18 am" src="https://cloud.githubusercontent.com/assets/103879/22429165/b0023080-e6d7-11e6-8852-2fda71fff123.png">

Not able to reproduce this.  The copilot only received an email after joining the project.
