### ISSUE TITLE
Add Slackbot notification when project has been claimed by copilot

### ISSUE THREAD

**Issue by fnisen** [topcoder-platform/tc-connect-notifications#62]
Would be good to let copilots know when a project is no longer available, so they don't need to click through unnecessarily

**Comment by parthshah** [comment]
Post a message only when a copilot is added in 'is_review' or 'active' project status and total copilot count is < 2.
@fnisen - we should restrict it to these 2 states to ensure a message is posted only if the project was available to be claimed at some time.  
**Note:** Please provide the text for the slack notification

**Comment by fnisen** [comment]
@parthshah that's good thinking, but shouldn't it actually be when a copilot is added in "reviewed" phase? That's the phase that makes a project claimable for copilots. 

- For the copy, can we actually show the handle of the copilot in the message? So, copy would be: 
"(Copilot handle) has claimed a project. Welcome to the team!" And then the rest of the attributes: Title, Description, Project type, post time
- Option 2 would be putting the copilot name in the Slack post body. Let me know if that's the only way to do it or is much easier of an implementation

- Also, can we change the avatars, like so, to make the difference more obvious: 
--- Original post: 
<img width="45" alt="screen shot 2017-02-07 at 4 12 18 pm" src="https://cloud.githubusercontent.com/assets/12552247/22717529/684fcc28-ed50-11e6-8cba-8d97813dff53.png">
--- Follow up post that project has been claimed:
<img width="43" alt="screen shot 2017-02-07 at 4 12 26 pm" src="https://cloud.githubusercontent.com/assets/12552247/22717532/709df058-ed50-11e6-8d39-7b30865c7fbd.png">
I can get these icons from Vic in case you don't have them already.

**Comment by parthshah** [comment]
➤ Parth commented:
I would like to include active state as well, in case a project manager goes moves it to active state without adding a copilot.
Yes we can use those avatars -- @uttpal please see above
