### ISSUE TITLE
Change copy and avatar for recurring copilot notifications

### ISSUE THREAD

**Issue by fnisen** [topcoder-platform/tc-connect-notifications#65]
Would be a good to indicate that a project is going unclaimed to make it easier to differentiate from one that is new, so that copilots know whether they've already seen it. Can we change the copy to: 
"We're still looking for a copilot for a reviewed project. Please check it out and claim it." And use the Coder error avatar (not sure if it's possible to use different avatars for the same Slackbot)....

**Comment by parthshah** [comment]
Please overwrite the default avatar with : https://emoji.slack-edge.com/T03R80JP7/coder-error/cd2633216e7fd385.png

**Comment by fnisen** [comment]
Right, just to clarify all the avatars, related to my comment on this issue https://github.com/topcoder-platform/tc-connect-notifications/issues/62#issuecomment-278188008

- When a project is first posted to copilots, use this one: https://emoji.slack-edge.com/T03R80JP7/coder-the-bot/85ae574c0c7063ef.png (if you want, this can also be the default for manager notifications, too)
- When a project is unclaimed and we repost to copilots, use this one: https://emoji.slack-edge.com/T03R80JP7/coder-error/cd2633216e7fd385.png
- When a project is claimed, use this one: https://emoji.slack-edge.com/T03R80JP7/coder-grinning/a3b7f3fe9e838377.png

Thank you.
