### ISSUE TITLE
Fix typos in Ownership changed notifications

### ISSUE THREAD

**Issue by parthshah** [topcoder-platform/tc-connect-notifications#70]
1. missing an "&", so the sentence should read "Your project has a new owner & Hugo Robles..." (FN: We missed a period here. "Your project has a new owner. Hugo Robles....")
2. Project title is not being picked up. (FN: it's not being resolved in the app, nor by email).

**Comment by vikasrohit** [comment]
Closing at changes are already there and project title updates can not be picked by slack or emails.
