### ISSUE TITLE
Slack posts are not working for reviewed projects

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-connect-notifications#77]
Since last few weeks, we are missing few projects from Slack posts to the copilots channel.

**Comment by talesforce** [comment]
That explains why we've not seen any new activity on Slack for self service projects, hopefully this can be fixed quickly.

**Comment by vikasrohit** [comment]
Should be fixed now in dev.

**Comment by vikasrohit** [comment]
Closing as it is working fine in production as well.
